"""`tier_threshold_cents` and `tier_rate` are never parametrized in this file --
they're generated by `pytest_generate_tests` in conftest.py, straight from
DISCOUNT_TIERS. Run
    uv run pytest modules/02-parametrization/examples/test_generated_boundaries.py -v
and compare the case ids against src/shop/domain/pricing.py's DISCOUNT_TIERS table.
"""

from __future__ import annotations

from decimal import ROUND_HALF_UP, Decimal

from shop.domain.pricing import calculate_discount_cents


def test_discount_at_exactly_each_tier_threshold(
    tier_threshold_cents: int, tier_rate: float
) -> None:
    expected = int(
        (Decimal(tier_threshold_cents) * Decimal(str(tier_rate))).quantize(
            Decimal("1"), rounding=ROUND_HALF_UP
        )
    )

    assert calculate_discount_cents(tier_threshold_cents) == expected
